# Generated by Django 4.2.2 on 2023-10-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvarient_sizevarient_product_colour_varient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorvarient',
            old_name='colour_name',
            new_name='color_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='colour_varient',
            new_name='color_varient',
        ),
    ]
